baseURL: "https://workshop.bpf.sh/"
languageCode: "en-us"
title: "BPF Workshop"
theme: "workshop"
publishDir: "docs"

menu:
 main:
   - identifier: introduction
     weight: 100
     title: "Introduction"
   - identifier: bpf-vm 
     weight: 300
     title: "The BPF in Kernel Virtual Machine"
   - identifier: bcc 
     weight: 400
     title: "BCC"
   - identifier: bpftrace
     weight: 500
     title: "bpftrace"
   - identifier: kubernetes
     weight: 700
     title: "eBPF and Kubernetes"
   - identifier: networking
     weight: 1000
     title: "eBPF and Linux Networking"
   - identifier: security
     weight: 1100
     title: "Linux Kernel security and eBPF"
